config/routes.rb
Rails.application.routes.draw do
  get "login" , to: "sessions#new"
  post "login" , to: "sessions#create"
  get "signup" , to: "users#new"
  delete "logout" , to: "sessions#destroy"
  resources :users, except: [:new]
  post "message" ,to: "messages#create"
  # Defines the root path route ("/")
    root "chatroom#index"
    mount ActionCable.server,at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validate :body
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validate :username
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,:logged_in?;
  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:error]="You must be logged in";
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @messages=Message.all
    @message=Message.new
    end

  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",{  mod_message: message_render(message) }
    
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :logged_in_redirect , only: [:new,:create]

  def new
  end

  def create
  user=User.find_by(username:params[:session][:username])
  if user && user.authenticate(params[:session][:password])
    session[:user_id]=user.id
    flash[:notice]="You logged in success"
    redirect_to root_path
  else

    flash[:now]="Enter full details"
      render 'new'
  end
  end

  def destroy
    session[:user_id]=nil
    flash[:error]="You were logged out"
    redirect_to root_path, status: :see_other
  end
 private
 def logged_in_redirect
   if logged_in?
     flash[:error]="your already logged in"
     redirect_to root_path
 end
end
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#   before_action :set_user, only: [:show, :edit, :update]
#
#   def show
#     @articles = @user.articles.paginate(page: params[:page], per_page: 5)
#   end
#
#   def index
#     @users = User.paginate(page: params[:page], per_page: 5)
#   end
#
#   def new
#     @user = User.new
#   end
#
#   def edit
#   end
#
#   def update
#     if @user.update(user_params)
#       flash[:notice] = "Your account information was successfully updated"
#       redirect_to @user
#     else
#       render 'edit'
#     end
#   end
#
#   def create
#     @user = User.new(user_params)
#     if @user.save
#       session[:user_id] = @user.id
#       flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
#       redirect_to articles_path
#     else
#       render 'new'
#     end
#   end
#
#   private
#   def user_params
#     params.require(:user).permit(:username, :email, :password)
#   end
#
#   def set_user
#     @user = User.find(params[:id])
#   end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class="header">
    <div class="container justify-content-center text-center">
        <div class="icon d-block my-4">
            <%=image_tag("home/icon.png",class:"image")%>
                <p class="icon-title">SAY SOMETHONG</p>
        </div>
    </div>
</div>
<div class="chat-window">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-md-9">

                <div class="card">
                    <div class="card-header">
                        Featured
                    </div>
                    <div class="card-body" id="message-container">
                        <%= render @messages %>
                    </div>

                    <%=form_with scope: :message,url: message_path ,remote: false,class:"form",data: {turbo: false}  do |f|%>
                        <div class="card-footer">
                            <div class="input-group mb-3">
                                <%= f.text_field :body ,class:"form-control", placeholder:"enter message"%>
                                    <%=f.button "Submit", class:"btn btn-outline-success"%>
                            </div>
                        </div>
                        <%end%>

                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        Featured
                    </div>
                    <div class="card-body">
                        <div class="btn-group-vertical card__menu rounded">
                            <a href="#" class="btn card__menu-btn">Home</a>
                            <a href="#" class="btn card__menu-btn">Messages</a>
                            <a href="#" class="btn card__menu-btn">Friends</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message_content|%>
<div class="alert alert-info alert-dismissible fade show">
    <strong>Info!</strong> <%=message_content%>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">imessage</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Chatroom</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Messages</a>
        </li>
        </ul>
      <!-- Example split danger button -->
      <div class="dropdown me-2  ">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Account
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <%if logged_in?%>
          <%=link_to "logout",logout_path, data:{turbo_method: :delete        }, class:"dropdown-item"%>
          <% else%>
            <%=link_to "login",login_path, class:"dropdown-item"%>
          <%end%>
         <li><a class="dropdown-item" href="#"></a></li>
        </ul>
      </div>
      <% if !logged_in?%>
     <%=link_to "login",login_path, class:"btn btn-outline-success"%>
     <%end%>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <%=favicon_link_tag%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
   <div class="container-fluid">
    <%= render "layouts/messages"%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<ol class="list-group list-group-flush">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold small messages">   <%=message.body%> </div>

    </div>
    <span class="fw-light  text-muted"><%=message.user.username%></span>
  </li>
</ol>